/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.FuriniSolutions.view.notafiscal;

import br.com.FuriniSolutions.bean.Cliente;
import br.com.FuriniSolutions.bean.NotaFiscal;
import br.com.FuriniSolutions.dao.ClienteDAO;
import br.com.FuriniSolutions.dao.NotaFiscalDAO;
import br.com.FuriniSolutions.model.ClienteComboBoxModel;
import br.com.FuriniSolutions.model.NotaFiscalTableModel;
import br.com.FuriniSolutions.util.Observer;
import br.com.FuriniSolutions.util.LoadingDialog;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author lucas
 */
public class NotaFiltroCliente extends javax.swing.JFrame implements Observer {

    private List<NotaFiscal> notas = new ArrayList<>();
    NotaFiscalTableModel tableModel = new NotaFiscalTableModel();
    NotaFiscal notaselecionada = new NotaFiscal();

    public NotaFiltroCliente() {

        initComponents();

        //colocando a mascara NOS TEXT FIELD
        jbtnVisualizar.setEnabled(false);

        //setando o combobox de cliente
        //criando o modedlo
        ClienteDAO clienteDao = new ClienteDAO();
        ClienteComboBoxModel comboboxModel = new ClienteComboBoxModel(clienteDao.findAll());
        comboboxCliente.setModel(comboboxModel);

        tableNotas.setModel(tableModel);
        buscarProdutos();

    }

    private void buscarProdutos() {
        // Cria a tela de carregamento, passando a janela atual como pai
        LoadingDialog loadingDialog = new LoadingDialog(this);

        // Cria o SwingWorker para carregar os dados em background
        SwingWorker<List<NotaFiscal>, Void> worker = new SwingWorker<>() {
            @Override
            protected List<NotaFiscal> doInBackground() throws Exception {
                NotaFiscalDAO notaDAO = new NotaFiscalDAO();
                return notaDAO.findAll();
            }

            @Override
            protected void done() {
                try {
                    List<NotaFiscal> notasRetornadas = get();
                    NotaFiscalTableModel tableModel = (NotaFiscalTableModel) tableNotas.getModel();
                    tableModel.clear();
                    tableModel.addList(notasRetornadas);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(NotaFiltroCliente.this, "Erro ao buscar produtos: " + e.getMessage());
                } finally {
                    // Fecha o diálogo de carregamento
                    loadingDialog.dispose();
                }
            }
        };

        // Inicia o carregamento dos dados
        worker.execute();

        // Exibe o diálogo de carregamento (modal)
        loadingDialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayerCliente = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        buttonFiltrar = new javax.swing.JButton();
        comboboxCliente = new javax.swing.JComboBox<>();
        jbtnVisualizar = new javax.swing.JButton();
        jbtnNovaNota = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNotas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filtro de Notas por Cliente");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLayerCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        jLabel2.setText("Nome do cliente:");

        buttonFiltrar.setText("Filtrar");
        buttonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFiltrarActionPerformed(evt);
            }
        });

        comboboxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxClienteActionPerformed(evt);
            }
        });

        jLayerCliente.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayerCliente.setLayer(buttonFiltrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayerCliente.setLayer(comboboxCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayerClienteLayout = new javax.swing.GroupLayout(jLayerCliente);
        jLayerCliente.setLayout(jLayerClienteLayout);
        jLayerClienteLayout.setHorizontalGroup(
            jLayerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayerClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboboxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonFiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayerClienteLayout.setVerticalGroup(
            jLayerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayerClienteLayout.createSequentialGroup()
                .addGroup(jLayerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(buttonFiltrar)
                    .addComponent(comboboxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jbtnVisualizar.setText("Visualizar");
        jbtnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVisualizarActionPerformed(evt);
            }
        });

        jbtnNovaNota.setText("Nova nota");
        jbtnNovaNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNovaNotaActionPerformed(evt);
            }
        });

        tableNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableNotas);

        jLayeredPane1.setLayer(jLayerCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbtnVisualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbtnNovaNota, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jbtnNovaNota)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtnVisualizar)))
                    .addComponent(jLayerCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jLayerCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnVisualizar)
                    .addComponent(jbtnNovaNota))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVisualizarActionPerformed
        NotaVisualizar view = new NotaVisualizar(notaselecionada);
        view.setVisible(true);
    }//GEN-LAST:event_jbtnVisualizarActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
    }//GEN-LAST:event_formWindowGainedFocus

    private void buttonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFiltrarActionPerformed
        //setando as variaveis para o filtro        
        Cliente cliente = (Cliente) comboboxCliente.getSelectedItem();

        try {
            NotaFiscalDAO notaDao = new NotaFiscalDAO();

            notas = notaDao.buscarNotasClienteEspecifico(cliente);
            NotaFiscalTableModel tableModel = (NotaFiscalTableModel) tableNotas.getModel();
            tableModel.clear();
            tableModel.addList(notas);

        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar produtos: " + e.getMessage());
        }

    }//GEN-LAST:event_buttonFiltrarActionPerformed

    private void comboboxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxClienteActionPerformed

    private void jbtnNovaNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNovaNotaActionPerformed

        NotaCreate view = new NotaCreate();
        view.addObserver(this); // adicionando um observer
        view.setVisible(true);
    }//GEN-LAST:event_jbtnNovaNotaActionPerformed

    public static LocalDate converterTextoParaLocalDate(String texto) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        try {
            return LocalDate.parse(texto, formatter);
        } catch (DateTimeParseException e) {
            return null; // Retorna null se a data for inválida
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotaFiltroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotaFiltroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotaFiltroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotaFiltroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotaFiltroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFiltrar;
    private javax.swing.JComboBox<Cliente> comboboxCliente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayerCliente;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnNovaNota;
    private javax.swing.JButton jbtnVisualizar;
    private javax.swing.JTable tableNotas;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(NotaFiscal notaNova) {
        tableModel.add(notaNova);
        tableModel.fireTableDataChanged();
    }

}
