/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.FuriniSolutions.view.notafiscal;

import br.com.FuriniSolutions.bean.NotaFiscal;
import br.com.FuriniSolutions.dao.NotaFiscalDAO;
import br.com.FuriniSolutions.model.NotaFiscalTableModel;
import br.com.FuriniSolutions.util.LoadingDialog;
import br.com.FuriniSolutions.util.Observer;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author lucas
 */
public class NotaFiltroClienteIntervalo extends javax.swing.JFrame implements Observer {

    private List<NotaFiscal> notas = new ArrayList<>();
    NotaFiscalTableModel tableModel = new NotaFiscalTableModel();
    NotaFiscal notaselecionada = new NotaFiscal();
    MaskFormatter mfdataInicio;
    MaskFormatter mfdataFim;

    public NotaFiltroClienteIntervalo() {

        //criando a mascara para a data
        try {
            mfdataInicio = new MaskFormatter("##/##/####");
            mfdataFim = new MaskFormatter("##/##/####");
        } catch (ParseException e) {
            System.out.println(e);
        }

        initComponents();

        //colocando a mascara NOS TEXT FIELD
        textDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mfdataInicio));
        textDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mfdataFim));

        jbtnVisualizar.setEnabled(false);

        //btn com problemas many connections
        //jbtnVisualizar.setEnabled(false);
        tableNotas.setModel(tableModel);

        buscarProdutos();

        tableNotas.getSelectionModel().addListSelectionListener(event -> {
            if (!event.getValueIsAdjusting()) { // Evita múltiplas chamadas durante o ajuste da seleção
                int linha = tableNotas.getSelectedRow();

                if (linha >= 0) { // Garante que há uma linha selecionada
                    NotaFiscal nota = tableModel.getNota(linha);
                    notaselecionada = nota;
                    jbtnVisualizar.setEnabled(nota != null); // Ativa o botão apenas se houver nota
                } else {
                    jbtnVisualizar.setEnabled(false); // Desativa o botão se nada estiver selecionado
                }
            }
        });
    }

    private void buscarProdutos() {
        // Cria a tela de carregamento, passando a janela atual como pai
        LoadingDialog loadingDialog = new LoadingDialog(this);

        // Cria o SwingWorker para carregar os dados em background
        SwingWorker<List<NotaFiscal>, Void> worker = new SwingWorker<>() {
            @Override
            protected List<NotaFiscal> doInBackground() throws Exception {
                NotaFiscalDAO notaDAO = new NotaFiscalDAO();
                return notaDAO.findAll();
            }

            @Override
            protected void done() {
                try {
                    List<NotaFiscal> notasRetornadas = get();
                    NotaFiscalTableModel tableModel = (NotaFiscalTableModel) tableNotas.getModel();
                    tableModel.clear();
                    tableModel.addList(notasRetornadas);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(NotaFiltroClienteIntervalo.this, "Erro ao buscar produtos: " + e.getMessage());
                } finally {
                    // Fecha o diálogo de carregamento
                    loadingDialog.dispose();
                }
            }
        };
        
        // Inicia o carregamento dos dados
        worker.execute();

        // Exibe o diálogo de carregamento (modal)
        loadingDialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked");
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayerCliente = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonFiltrar = new javax.swing.JButton();
        textDataInicio = new javax.swing.JFormattedTextField(mfdataInicio);
        textDataFim = new javax.swing.JFormattedTextField(mfdataFim);
        jLabel3 = new javax.swing.JLabel();
        jbtnVisualizar = new javax.swing.JButton();
        jbtnNovaNota = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNotas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta e Filtro de Notas");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLayerCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        jLabel2.setText("Nome do cliente:");

        textNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textNomeMouseClicked(evt);
            }
        });
        textNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textNomeKeyReleased(evt);
            }
        });

        jLabel1.setText("até");

        buttonFiltrar.setText("Filtrar");
        buttonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFiltrarActionPerformed(evt);
            }
        });

        textDataInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textDataInicioFocusLost(evt);
            }
        });
        textDataInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDataInicioActionPerformed(evt);
            }
        });

        textDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        textDataFim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textDataFimFocusLost(evt);
            }
        });
        textDataFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDataFimActionPerformed(evt);
            }
        });

        jLabel3.setText("Intervalo de");

        jLayerCliente.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayerCliente.setLayer(textNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayerCliente.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayerCliente.setLayer(buttonFiltrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayerCliente.setLayer(textDataInicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayerCliente.setLayer(textDataFim, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayerCliente.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayerClienteLayout = new javax.swing.GroupLayout(jLayerCliente);
        jLayerCliente.setLayout(jLayerClienteLayout);
        jLayerClienteLayout.setHorizontalGroup(
            jLayerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayerClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(buttonFiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayerClienteLayout.setVerticalGroup(
            jLayerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayerClienteLayout.createSequentialGroup()
                .addGroup(jLayerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(buttonFiltrar)
                    .addComponent(textDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jbtnVisualizar.setText("Visualizar");
        jbtnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVisualizarActionPerformed(evt);
            }
        });

        jbtnNovaNota.setText("Nova nota");
        jbtnNovaNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNovaNotaActionPerformed(evt);
            }
        });

        tableNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableNotas);

        jLayeredPane1.setLayer(jLayerCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbtnVisualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbtnNovaNota, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayerCliente)
                    .addComponent(jScrollPane1))
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnNovaNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnVisualizar)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jLayerCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnVisualizar)
                    .addComponent(jbtnNovaNota))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNovaNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNovaNotaActionPerformed

        NotaCreate view = new NotaCreate();
        view.addObserver(this); // adicionando um observer
        view.setVisible(true);
    }//GEN-LAST:event_jbtnNovaNotaActionPerformed

    private void jbtnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVisualizarActionPerformed
        NotaVisualizar view = new NotaVisualizar(notaselecionada);
        view.setVisible(true);
    }//GEN-LAST:event_jbtnVisualizarActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
    }//GEN-LAST:event_formWindowGainedFocus

    private void textNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textNomeMouseClicked

    }//GEN-LAST:event_textNomeMouseClicked

    private void textNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNomeKeyReleased

    }//GEN-LAST:event_textNomeKeyReleased

    private void textDataInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDataInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDataInicioActionPerformed

    private void textDataFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDataFimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDataFimActionPerformed

    private void textDataInicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textDataInicioFocusLost
        SimpleDateFormat sdt = new SimpleDateFormat("dd/MM/yyyy");
        sdt.setLenient(false); // impede que datas inválidas 

        String texto = textDataInicio.getText().replaceAll("[^0-9]", "").trim();

        if (texto.isEmpty()) {
            textDataInicio.setValue(null);
            textDataInicio.setText("");
            return; // Sai da função para evitar exibir erro
        }

        try {
            Date date = sdt.parse(textDataInicio.getText().trim());
            textDataInicio.setValue(sdt.format(date));
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Data inválida! Digite no formato dd/MM/yyyy.",
                    "Erro", JOptionPane.ERROR_MESSAGE);
            textDataInicio.setText("");
            textDataInicio.setValue(null);
        }
    }//GEN-LAST:event_textDataInicioFocusLost

    private void textDataFimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textDataFimFocusLost
        SimpleDateFormat sdt = new SimpleDateFormat("dd/MM/yyyy");
        sdt.setLenient(false); // impede que datas inválidas 

        String texto = textDataFim.getText().replaceAll("[^0-9]", "").trim();

        if (texto.isEmpty()) {
            textDataFim.setValue(null);
            textDataFim.setText("");
            return; // Sai da função para evitar exibir erro
        }

        try {
            Date date = sdt.parse(textDataFim.getText().trim());
            textDataFim.setValue(sdt.format(date));
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Data inválida! Digite no formato dd/MM/yyyy.",
                    "Erro", JOptionPane.ERROR_MESSAGE);
            textDataFim.setText("");
            textDataFim.setValue(null);
        }
    }//GEN-LAST:event_textDataFimFocusLost

    private void buttonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFiltrarActionPerformed
        //setando as variaveis para o filtro
        LocalDate dataInicio = converterTextoParaLocalDate(textDataInicio.getText());
        LocalDate dataFim = converterTextoParaLocalDate(textDataFim.getText());
        String nome = textNome.getText();

        try {
            NotaFiscalDAO notaDao = new NotaFiscalDAO();

            notas = notaDao.filtrarNotasPorClienteEIntervaloDeDatas(nome, dataInicio, dataFim);

            NotaFiscalTableModel tableModel = (NotaFiscalTableModel) tableNotas.getModel();
            tableModel.clear();
            tableModel.addList(notas);

        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar produtos: " + e.getMessage());
        }

    }//GEN-LAST:event_buttonFiltrarActionPerformed

    public static LocalDate converterTextoParaLocalDate(String texto) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        try {
            return LocalDate.parse(texto, formatter);
        } catch (DateTimeParseException e) {
            return null; // Retorna null se a data for inválida
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotaFiltroClienteIntervalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotaFiltroClienteIntervalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotaFiltroClienteIntervalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotaFiltroClienteIntervalo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotaFiltroClienteIntervalo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFiltrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayerCliente;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnNovaNota;
    private javax.swing.JButton jbtnVisualizar;
    private javax.swing.JTable tableNotas;
    private javax.swing.JFormattedTextField textDataFim;
    private javax.swing.JFormattedTextField textDataInicio;
    private javax.swing.JTextField textNome;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(NotaFiscal notaNova) {
        tableModel.add(notaNova);
        tableModel.fireTableDataChanged();
    }

}
