/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.FuriniSolutions.view.ItemNota;

import br.com.FuriniSolutions.bean.ItemNota;
import br.com.FuriniSolutions.bean.Produto;
import br.com.FuriniSolutions.dao.ItemNotaDAO;
import br.com.FuriniSolutions.dao.ProdutoDAO;
import br.com.FuriniSolutions.model.ItemNotaTableModel;
import br.com.FuriniSolutions.model.ProdutoTableModel;
import br.com.FuriniSolutions.util.LoadingDialog;
import br.com.FuriniSolutions.view.produto.ProdutoFiltroValor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author lucas
 */
public class ItemNotaFiltrar extends javax.swing.JFrame {

    private List<ItemNota> itens = new ArrayList<>();
    ItemNotaTableModel tableModel = new ItemNotaTableModel();

    public ItemNotaFiltrar() {

        initComponents();

        tableItensNota.setModel(tableModel);

        buscarItens();
    }

    private void buscarItens() {

        // Cria a tela de carregamento, passando a janela atual como pai
        LoadingDialog loadingDialog = new LoadingDialog(this);

        // Cria o SwingWorker para carregar os dados em background
        SwingWorker<List<ItemNota>, Void> worker = new SwingWorker<>() {
            @Override
            protected List<ItemNota> doInBackground() throws Exception {
                ItemNotaDAO itemDAO = new ItemNotaDAO();
                return itemDAO.findAll();
            }

            @Override
            protected void done() {
                try {
                    List<ItemNota> itensRetornados = get();
                    ItemNotaTableModel tableModel = (ItemNotaTableModel) tableItensNota.getModel();
                    tableModel.clear();
                    tableModel.addList(itensRetornados);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(ItemNotaFiltrar.this, "Erro ao buscar produtos: " + e.getMessage());
                } finally {
                    // Fecha o diálogo de carregamento
                    loadingDialog.dispose();
                }
            }
        };

        // Inicia o carregamento dos dados
        worker.execute();

        // Exibe o diálogo de carregamento (modal)
        loadingDialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableItensNota = new javax.swing.JTable();
        jLayerCliente = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        textProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buttonFiltrar = new javax.swing.JButton();
        textQuantidade = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta e Filtro de Itens da Nota");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        tableItensNota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableItensNota);

        jLayerCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        jLabel2.setText("Produto:");

        textProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textProdutoMouseClicked(evt);
            }
        });
        textProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textProdutoKeyReleased(evt);
            }
        });

        jLabel3.setText("Quantidade:");

        buttonFiltrar.setText("Filtrar");
        buttonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFiltrarActionPerformed(evt);
            }
        });

        textQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textQuantidadeFocusLost(evt);
            }
        });
        textQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textQuantidadeActionPerformed(evt);
            }
        });
        textQuantidade.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                textQuantidadePropertyChange(evt);
            }
        });

        jLayerCliente.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayerCliente.setLayer(textProduto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayerCliente.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayerCliente.setLayer(buttonFiltrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayerCliente.setLayer(textQuantidade, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayerClienteLayout = new javax.swing.GroupLayout(jLayerCliente);
        jLayerCliente.setLayout(jLayerClienteLayout);
        jLayerClienteLayout.setHorizontalGroup(
            jLayerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayerClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonFiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayerClienteLayout.setVerticalGroup(
            jLayerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayerClienteLayout.createSequentialGroup()
                .addGroup(jLayerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(buttonFiltrar)
                    .addComponent(textQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLayerCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayerCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
    }//GEN-LAST:event_formWindowGainedFocus

    private void textProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textProdutoMouseClicked

    }//GEN-LAST:event_textProdutoMouseClicked

    private void textProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textProdutoKeyReleased

    }//GEN-LAST:event_textProdutoKeyReleased

    private void textQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textQuantidadeActionPerformed

    private void textQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textQuantidadeFocusLost

    }//GEN-LAST:event_textQuantidadeFocusLost

    private void buttonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFiltrarActionPerformed
        //setando as variaveis para o filtro
        String produto = textProduto.getText();
        Integer quantidade = null;

        if (!textQuantidade.getText().equalsIgnoreCase("")) {
            quantidade = Integer.parseInt(textQuantidade.getText());
        }

        try {
            ItemNotaDAO itemDao = new ItemNotaDAO();

            itens = itemDao.filtrarItensPorProdutoEQuantidade(produto, quantidade);

            ItemNotaTableModel tableModel = (ItemNotaTableModel) tableItensNota.getModel();
            tableModel.clear();
            tableModel.addList(itens);

        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar itens de nota: " + e.getMessage());
        }

    }//GEN-LAST:event_buttonFiltrarActionPerformed

    private void textQuantidadePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_textQuantidadePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_textQuantidadePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemNotaFiltrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemNotaFiltrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemNotaFiltrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemNotaFiltrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemNotaFiltrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFiltrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayerCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableItensNota;
    private javax.swing.JTextField textProduto;
    private javax.swing.JFormattedTextField textQuantidade;
    // End of variables declaration//GEN-END:variables

}
