/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.FuriniSolutions.view.ItemNota;

import br.com.FuriniSolutions.bean.ItemNota;
import br.com.FuriniSolutions.bean.NotaFiscal;
import br.com.FuriniSolutions.dao.ItemNotaDAO;
import br.com.FuriniSolutions.dao.NotaFiscalDAO;
import br.com.FuriniSolutions.model.ItemNotaTableModel;
import br.com.FuriniSolutions.model.NotaFiscalTableModel;
import br.com.FuriniSolutions.model.RelatorioItemNotaTableModel;
import br.com.FuriniSolutions.util.LoadingDialog;
import br.com.FuriniSolutions.util.Observer;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author lucas
 */
public class RelatorioItensVendidos extends javax.swing.JFrame {

    private List<Object[]> itens = new ArrayList<>();
    RelatorioItemNotaTableModel tableModel = new RelatorioItemNotaTableModel();
    MaskFormatter mfdataInicio;
    MaskFormatter mfdataFim;

    public RelatorioItensVendidos() {

        //criando a mascara para a data
        try {
            mfdataInicio = new MaskFormatter("##/##/####");
            mfdataFim = new MaskFormatter("##/##/####");
        } catch (ParseException e) {
            System.out.println(e);
        }

        initComponents();

        //colocando a mascara NOS TEXT FIELD
        textDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mfdataInicio));
        textDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(mfdataFim));

        //setando o model na tabela
        tableItens.setModel(tableModel);

        //busca os itens
        buscarItens();

    }

    private void buscarItens() {

        // Cria a tela de carregamento, passando a janela atual como pai
        LoadingDialog loadingDialog = new LoadingDialog(this);

        // Cria o SwingWorker para carregar os dados em background
        SwingWorker<List<Object[]>, Void> worker = new SwingWorker<>() {
            @Override
            protected List<Object[]> doInBackground() throws Exception {
                ItemNotaDAO itemDAO = new ItemNotaDAO();
                return itemDAO.gerarRelatorioItensVendidosPorIntervalo(null, null);
            }

            @Override
            protected void done() {
                try {
                    List<Object[]> itensRetornados = get();
                    RelatorioItemNotaTableModel tableModel = (RelatorioItemNotaTableModel) tableItens.getModel();
                    tableModel.clear();
                    tableModel.addList(itensRetornados);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(RelatorioItensVendidos.this, "Erro ao buscar produtos: " + e.getMessage());
                } finally {
                    // Fecha o diálogo de carregamento
                    loadingDialog.dispose();
                }
            }
        };

        // Inicia o carregamento dos dados
        worker.execute();

        // Exibe o diálogo de carregamento (modal)
        loadingDialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked");
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayerCliente = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        buttonGerarRelatorio = new javax.swing.JButton();
        textDataInicio = new javax.swing.JFormattedTextField(mfdataInicio);
        textDataFim = new javax.swing.JFormattedTextField(mfdataFim);
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableItens = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Produtos mais vendidos");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLayerCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        jLabel1.setText("até");

        buttonGerarRelatorio.setText("Gerar Relatório");
        buttonGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGerarRelatorioActionPerformed(evt);
            }
        });

        textDataInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textDataInicioFocusLost(evt);
            }
        });
        textDataInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDataInicioActionPerformed(evt);
            }
        });

        textDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        textDataFim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textDataFimFocusLost(evt);
            }
        });
        textDataFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDataFimActionPerformed(evt);
            }
        });

        jLabel3.setText("Intervalo de");

        jLayerCliente.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayerCliente.setLayer(buttonGerarRelatorio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayerCliente.setLayer(textDataInicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayerCliente.setLayer(textDataFim, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayerCliente.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayerClienteLayout = new javax.swing.GroupLayout(jLayerCliente);
        jLayerCliente.setLayout(jLayerClienteLayout);
        jLayerClienteLayout.setHorizontalGroup(
            jLayerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayerClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(textDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(textDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonGerarRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayerClienteLayout.setVerticalGroup(
            jLayerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayerClienteLayout.createSequentialGroup()
                .addGroup(jLayerClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(buttonGerarRelatorio)
                    .addComponent(textDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        tableItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableItens);

        jLayeredPane1.setLayer(jLayerCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayerCliente)
            .addComponent(jScrollPane1)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jLayerCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
    }//GEN-LAST:event_formWindowGainedFocus

    private void textDataInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDataInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDataInicioActionPerformed

    private void textDataFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDataFimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDataFimActionPerformed

    private void textDataInicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textDataInicioFocusLost
        //esse metodo tem que existir, porque da erro ao tentar apagar o input ele rememora o ultima data digitada
        SimpleDateFormat sdt = new SimpleDateFormat("dd/MM/yyyy");
        sdt.setLenient(false); // impede que datas inválidas 

        String texto = textDataInicio.getText().replaceAll("[^0-9]", "").trim();

        if (texto.isEmpty()) {
            textDataInicio.setValue(null);
            textDataInicio.setText("");
            return; // Sai da função para evitar exibir erro
        }

        try {
            Date date = sdt.parse(textDataInicio.getText().trim());
            textDataInicio.setValue(sdt.format(date));
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Data inválida! Digite no formato dd/MM/yyyy.",
                    "Erro", JOptionPane.ERROR_MESSAGE);
            textDataInicio.setText("");
            textDataInicio.setValue(null);
        }
    }//GEN-LAST:event_textDataInicioFocusLost

    private void textDataFimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textDataFimFocusLost
        SimpleDateFormat sdt = new SimpleDateFormat("dd/MM/yyyy");
        sdt.setLenient(false); // impede que datas inválidas 

        String texto = textDataFim.getText().replaceAll("[^0-9]", "").trim();

        if (texto.isEmpty()) {
            textDataFim.setValue(null);
            textDataFim.setText("");
            return; // Sai da função para evitar exibir erro
        }

        try {
            Date date = sdt.parse(textDataFim.getText().trim());
            textDataFim.setValue(sdt.format(date));
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Data inválida! Digite no formato dd/MM/yyyy.",
                    "Erro", JOptionPane.ERROR_MESSAGE);
            textDataFim.setText("");
            textDataFim.setValue(null);
        }
    }//GEN-LAST:event_textDataFimFocusLost

    private void buttonGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGerarRelatorioActionPerformed
        //setando as variaveis para o filtro
        LocalDate dataInicio = converterTextoParaLocalDate(textDataInicio.getText());
        LocalDate dataFim = converterTextoParaLocalDate(textDataFim.getText());

        try {
            ItemNotaDAO itemDao = new ItemNotaDAO();

            itens = itemDao.gerarRelatorioItensVendidosPorIntervalo(dataInicio, dataFim);

            RelatorioItemNotaTableModel tableModel = (RelatorioItemNotaTableModel) tableItens.getModel();
            tableModel.clear();
            tableModel.addList(itens);

        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar produtos: " + e.getMessage());
        }

    }//GEN-LAST:event_buttonGerarRelatorioActionPerformed

    public static LocalDate converterTextoParaLocalDate(String texto) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        try {
            return LocalDate.parse(texto, formatter);
        } catch (DateTimeParseException e) {
            return null; // Retorna null se a data for inválida
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioItensVendidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioItensVendidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioItensVendidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioItensVendidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioItensVendidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGerarRelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayerCliente;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableItens;
    private javax.swing.JFormattedTextField textDataFim;
    private javax.swing.JFormattedTextField textDataInicio;
    // End of variables declaration//GEN-END:variables

}
